// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_role_common.proto

package suoha

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 性别
type RoleSex int32

const (
	RoleSex_man   RoleSex = 0
	RoleSex_woman RoleSex = 1
)

var RoleSex_name = map[int32]string{
	0: "man",
	1: "woman",
}
var RoleSex_value = map[string]int32{
	"man":   0,
	"woman": 1,
}

func (x RoleSex) Enum() *RoleSex {
	p := new(RoleSex)
	*p = x
	return p
}
func (x RoleSex) String() string {
	return proto.EnumName(RoleSex_name, int32(x))
}
func (x *RoleSex) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RoleSex_value, data, "RoleSex")
	if err != nil {
		return err
	}
	*x = RoleSex(value)
	return nil
}
func (RoleSex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_role_common_d87c465b943b8096, []int{0}
}

// 终端类型
type GameTerminalType int32

const (
	GameTerminalType_game_terminal_type_reserve GameTerminalType = 0
	GameTerminalType_pc                         GameTerminalType = 1
	GameTerminalType_ios_width                  GameTerminalType = 2
	GameTerminalType_ios_hight                  GameTerminalType = 3
	GameTerminalType_and_widht                  GameTerminalType = 4
	GameTerminalType_and_hight                  GameTerminalType = 5
	GameTerminalType_ort_wight                  GameTerminalType = 6
	GameTerminalType_ort_hight                  GameTerminalType = 7
)

var GameTerminalType_name = map[int32]string{
	0: "game_terminal_type_reserve",
	1: "pc",
	2: "ios_width",
	3: "ios_hight",
	4: "and_widht",
	5: "and_hight",
	6: "ort_wight",
	7: "ort_hight",
}
var GameTerminalType_value = map[string]int32{
	"game_terminal_type_reserve": 0,
	"pc":        1,
	"ios_width": 2,
	"ios_hight": 3,
	"and_widht": 4,
	"and_hight": 5,
	"ort_wight": 6,
	"ort_hight": 7,
}

func (x GameTerminalType) Enum() *GameTerminalType {
	p := new(GameTerminalType)
	*p = x
	return p
}
func (x GameTerminalType) String() string {
	return proto.EnumName(GameTerminalType_name, int32(x))
}
func (x *GameTerminalType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameTerminalType_value, data, "GameTerminalType")
	if err != nil {
		return err
	}
	*x = GameTerminalType(value)
	return nil
}
func (GameTerminalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_role_common_d87c465b943b8096, []int{1}
}

// 角色信息
type RoleInfo struct {
	Account      string  `protobuf:"bytes,1,req,name=account" json:"account"`
	AgentId      int64   `protobuf:"varint,2,req,name=agent_id,json=agentId" json:"agent_id"`
	OwnerId      int64   `protobuf:"varint,3,req,name=owner_id,json=ownerId" json:"owner_id"`
	Chips        uint64  `protobuf:"varint,4,req,name=chips" json:"chips"`
	Nickname     string  `protobuf:"bytes,5,req,name=nickname" json:"nickname"`
	Level        uint32  `protobuf:"varint,6,req,name=level" json:"level"`
	Avatar       uint32  `protobuf:"varint,7,req,name=avatar" json:"avatar"`
	Sex          RoleSex `protobuf:"varint,8,req,name=sex,enum=suoha.RoleSex" json:"sex"`
	IsNew        bool    `protobuf:"varint,9,opt,name=is_new,json=isNew" json:"is_new"`
	IsMainWallet bool    `protobuf:"varint,10,req,name=is_main_wallet,json=isMainWallet" json:"is_main_wallet"`
	MainWallet   uint64  `protobuf:"varint,11,opt,name=main_wallet,json=mainWallet" json:"main_wallet"`
	AutoWallet   bool    `protobuf:"varint,12,opt,name=auto_wallet,json=autoWallet" json:"auto_wallet"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_role_common_d87c465b943b8096, []int{0}
}
func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(dst, src)
}
func (m *RoleInfo) XXX_Size() int {
	return m.Size()
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RoleInfo) GetAgentId() int64 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *RoleInfo) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *RoleInfo) GetChips() uint64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *RoleInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RoleInfo) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RoleInfo) GetAvatar() uint32 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *RoleInfo) GetSex() RoleSex {
	if m != nil {
		return m.Sex
	}
	return RoleSex_man
}

func (m *RoleInfo) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func (m *RoleInfo) GetIsMainWallet() bool {
	if m != nil {
		return m.IsMainWallet
	}
	return false
}

func (m *RoleInfo) GetMainWallet() uint64 {
	if m != nil {
		return m.MainWallet
	}
	return 0
}

func (m *RoleInfo) GetAutoWallet() bool {
	if m != nil {
		return m.AutoWallet
	}
	return false
}

func init() {
	proto.RegisterType((*RoleInfo)(nil), "suoha.RoleInfo")
	proto.RegisterEnum("suoha.RoleSex", RoleSex_name, RoleSex_value)
	proto.RegisterEnum("suoha.GameTerminalType", GameTerminalType_name, GameTerminalType_value)
}
func (m *RoleInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoleInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(len(m.Account)))
	i += copy(dAtA[i:], m.Account)
	dAtA[i] = 0x10
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.AgentId))
	dAtA[i] = 0x18
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.OwnerId))
	dAtA[i] = 0x20
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.Chips))
	dAtA[i] = 0x2a
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(len(m.Nickname)))
	i += copy(dAtA[i:], m.Nickname)
	dAtA[i] = 0x30
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.Level))
	dAtA[i] = 0x38
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.Avatar))
	dAtA[i] = 0x40
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.Sex))
	dAtA[i] = 0x48
	i++
	if m.IsNew {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x50
	i++
	if m.IsMainWallet {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x58
	i++
	i = encodeVarintMsgRoleCommon(dAtA, i, uint64(m.MainWallet))
	dAtA[i] = 0x60
	i++
	if m.AutoWallet {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func encodeVarintMsgRoleCommon(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RoleInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	n += 1 + l + sovMsgRoleCommon(uint64(l))
	n += 1 + sovMsgRoleCommon(uint64(m.AgentId))
	n += 1 + sovMsgRoleCommon(uint64(m.OwnerId))
	n += 1 + sovMsgRoleCommon(uint64(m.Chips))
	l = len(m.Nickname)
	n += 1 + l + sovMsgRoleCommon(uint64(l))
	n += 1 + sovMsgRoleCommon(uint64(m.Level))
	n += 1 + sovMsgRoleCommon(uint64(m.Avatar))
	n += 1 + sovMsgRoleCommon(uint64(m.Sex))
	n += 2
	n += 2
	n += 1 + sovMsgRoleCommon(uint64(m.MainWallet))
	n += 2
	return n
}

func sovMsgRoleCommon(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMsgRoleCommon(x uint64) (n int) {
	return sovMsgRoleCommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RoleInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgRoleCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoleInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoleInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgRoleCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			m.AgentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerId", wireType)
			}
			m.OwnerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OwnerId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chips", wireType)
			}
			m.Chips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Chips |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nickname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgRoleCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nickname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			m.Avatar = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Avatar |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000040)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sex", wireType)
			}
			m.Sex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sex |= (RoleSex(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000080)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsNew", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsNew = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMainWallet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMainWallet = bool(v != 0)
			hasFields[0] |= uint64(0x00000100)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainWallet", wireType)
			}
			m.MainWallet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MainWallet |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoWallet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoWallet = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMsgRoleCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgRoleCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("account")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("agent_id")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("owner_id")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("chips")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("nickname")
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("level")
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("avatar")
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("sex")
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("is_main_wallet")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgRoleCommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgRoleCommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgRoleCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMsgRoleCommon
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsgRoleCommon
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsgRoleCommon(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsgRoleCommon = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgRoleCommon   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("msg_role_common.proto", fileDescriptor_msg_role_common_d87c465b943b8096)
}

var fileDescriptor_msg_role_common_d87c465b943b8096 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x73, 0x69, 0xd3, 0xf4, 0xcc, 0x85, 0xc8, 0x12, 0x92, 0x55, 0x50, 0xc6, 0x42, 0x42,
	0x44, 0x5d, 0x74, 0xc1, 0x23, 0xcc, 0xae, 0x0b, 0x58, 0xcc, 0x86, 0xa5, 0x65, 0x25, 0x87, 0xc6,
	0x22, 0xb6, 0xab, 0xd8, 0x6d, 0x86, 0xb7, 0x60, 0xc5, 0x13, 0xf0, 0x30, 0xb3, 0x9c, 0x25, 0x2b,
	0x84, 0xda, 0x17, 0x41, 0x4e, 0x9b, 0x2a, 0x68, 0x76, 0xf9, 0xff, 0xef, 0x3b, 0x3a, 0xf1, 0x81,
	0xd7, 0xca, 0x6e, 0x78, 0x6b, 0x1a, 0xe4, 0xa5, 0x51, 0xca, 0xe8, 0xd5, 0xb6, 0x35, 0xce, 0x90,
	0xa9, 0xdd, 0x99, 0x5a, 0x2c, 0x32, 0x4f, 0xc7, 0xe0, 0xdd, 0xaf, 0x18, 0xd2, 0x07, 0xd3, 0xe0,
	0x5a, 0x7f, 0x35, 0x24, 0x87, 0x99, 0x28, 0x4b, 0xb3, 0xd3, 0x8e, 0x86, 0x2c, 0x2a, 0xe6, 0xf7,
	0x93, 0xa7, 0x3f, 0x77, 0xc1, 0xc3, 0x50, 0x92, 0x3b, 0x48, 0xc5, 0x06, 0xb5, 0xe3, 0xb2, 0xa2,
	0x11, 0x8b, 0x8a, 0xf8, 0x22, 0xf8, 0x76, 0x5d, 0x79, 0xc1, 0x74, 0x1a, 0x5b, 0x2f, 0xc4, 0x63,
	0xa1, 0x6f, 0xd7, 0x15, 0x59, 0xc0, 0xb4, 0xac, 0xe5, 0xd6, 0xd2, 0x09, 0x8b, 0x8a, 0xc9, 0x99,
	0x9e, 0x2a, 0xc2, 0x20, 0xd5, 0xb2, 0xfc, 0xa6, 0x85, 0x42, 0x3a, 0x1d, 0xad, 0xbf, 0xb4, 0x7e,
	0xba, 0xc1, 0x3d, 0x36, 0x34, 0x61, 0x51, 0x71, 0x33, 0x4c, 0xf7, 0x15, 0x79, 0x0b, 0x89, 0xd8,
	0x0b, 0x27, 0x5a, 0x3a, 0x1b, 0xc1, 0x73, 0x47, 0x3e, 0x40, 0x6c, 0xf1, 0x91, 0xa6, 0x2c, 0x2a,
	0x6e, 0x3f, 0xbe, 0x5a, 0xf5, 0xd7, 0x58, 0xf5, 0x67, 0xb2, 0xf8, 0x78, 0x76, 0xbd, 0x41, 0xde,
	0x40, 0x22, 0x2d, 0xd7, 0xd8, 0xd1, 0x39, 0x0b, 0x8b, 0x74, 0xd8, 0x21, 0xed, 0x67, 0xec, 0xc8,
	0x12, 0x6e, 0xa5, 0xe5, 0x4a, 0x48, 0xcd, 0x3b, 0xd1, 0x34, 0xe8, 0x28, 0xb0, 0xe8, 0x22, 0x5d,
	0x4b, 0xfb, 0x49, 0x48, 0xfd, 0xa5, 0x27, 0xe4, 0x3d, 0x5c, 0x8d, 0xc5, 0x2b, 0x16, 0x5e, 0xde,
	0x0b, 0xea, 0x3f, 0x4d, 0xec, 0x9c, 0x19, 0xb4, 0xeb, 0xd1, 0x52, 0xf0, 0xe0, 0xa4, 0x2d, 0x73,
	0x48, 0x87, 0xbf, 0x25, 0x33, 0x88, 0x95, 0xd0, 0x59, 0x40, 0xe6, 0x30, 0xed, 0x8c, 0xff, 0x0c,
	0x97, 0x3f, 0x43, 0x20, 0x1b, 0xa1, 0x90, 0x3b, 0x6c, 0x95, 0xd4, 0xa2, 0xe1, 0xee, 0xfb, 0x16,
	0x49, 0x0e, 0x8b, 0x97, 0x2d, 0x6f, 0xd1, 0x62, 0xbb, 0xc7, 0x2c, 0x20, 0x09, 0x44, 0xdb, 0x32,
	0x0b, 0xc9, 0x0d, 0xcc, 0xa5, 0xb1, 0xbc, 0x93, 0x95, 0xab, 0xb3, 0x68, 0x88, 0xb5, 0xdc, 0xd4,
	0x2e, 0x8b, 0x7d, 0x14, 0xba, 0xf2, 0xb4, 0x76, 0xd9, 0x64, 0x88, 0x27, 0x3a, 0xf5, 0xd1, 0xb4,
	0x8e, 0x77, 0x7d, 0x4c, 0x86, 0x78, 0xa2, 0xb3, 0x7b, 0xfa, 0x74, 0xc8, 0xc3, 0xe7, 0x43, 0x1e,
	0xfe, 0x3d, 0xe4, 0xe1, 0x8f, 0x63, 0x1e, 0x3c, 0x1f, 0xf3, 0xe0, 0xf7, 0x31, 0x0f, 0xfe, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x73, 0x74, 0x62, 0xaa, 0x02, 0x00, 0x00,
}
