// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_broadcast.proto

package suoha

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 全局广播信息
type BcastworldResp struct {
	Content string `protobuf:"bytes,1,req,name=content" json:"content"`
}

func (m *BcastworldResp) Reset()         { *m = BcastworldResp{} }
func (m *BcastworldResp) String() string { return proto.CompactTextString(m) }
func (*BcastworldResp) ProtoMessage()    {}
func (*BcastworldResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_broadcast_f26ad4061139d112, []int{0}
}
func (m *BcastworldResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BcastworldResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BcastworldResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *BcastworldResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcastworldResp.Merge(dst, src)
}
func (m *BcastworldResp) XXX_Size() int {
	return m.Size()
}
func (m *BcastworldResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BcastworldResp.DiscardUnknown(m)
}

var xxx_messageInfo_BcastworldResp proto.InternalMessageInfo

func (m *BcastworldResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 广播消息 多语言
type BcastMsgResp struct {
	Msg *Dmsg `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
}

func (m *BcastMsgResp) Reset()         { *m = BcastMsgResp{} }
func (m *BcastMsgResp) String() string { return proto.CompactTextString(m) }
func (*BcastMsgResp) ProtoMessage()    {}
func (*BcastMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_broadcast_f26ad4061139d112, []int{1}
}
func (m *BcastMsgResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BcastMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BcastMsgResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *BcastMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcastMsgResp.Merge(dst, src)
}
func (m *BcastMsgResp) XXX_Size() int {
	return m.Size()
}
func (m *BcastMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BcastMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_BcastMsgResp proto.InternalMessageInfo

func (m *BcastMsgResp) GetMsg() *Dmsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

// 广播消息 多语言
type StopNoticePush struct {
	Id           uint32 `protobuf:"varint,1,req,name=id" json:"id"`
	Type         uint32 `protobuf:"varint,2,req,name=type" json:"type"`
	Executed     uint32 `protobuf:"varint,3,req,name=executed" json:"executed"`
	Content      string `protobuf:"bytes,4,req,name=content" json:"content"`
	StartTime    uint32 `protobuf:"varint,5,opt,name=start_time,json=startTime" json:"start_time"`
	EndTime      uint32 `protobuf:"varint,6,opt,name=end_time,json=endTime" json:"end_time"`
	IntervalTime uint32 `protobuf:"varint,7,opt,name=interval_time,json=intervalTime" json:"interval_time"`
}

func (m *StopNoticePush) Reset()         { *m = StopNoticePush{} }
func (m *StopNoticePush) String() string { return proto.CompactTextString(m) }
func (*StopNoticePush) ProtoMessage()    {}
func (*StopNoticePush) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_broadcast_f26ad4061139d112, []int{2}
}
func (m *StopNoticePush) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StopNoticePush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StopNoticePush.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *StopNoticePush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopNoticePush.Merge(dst, src)
}
func (m *StopNoticePush) XXX_Size() int {
	return m.Size()
}
func (m *StopNoticePush) XXX_DiscardUnknown() {
	xxx_messageInfo_StopNoticePush.DiscardUnknown(m)
}

var xxx_messageInfo_StopNoticePush proto.InternalMessageInfo

func (m *StopNoticePush) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StopNoticePush) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *StopNoticePush) GetExecuted() uint32 {
	if m != nil {
		return m.Executed
	}
	return 0
}

func (m *StopNoticePush) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *StopNoticePush) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *StopNoticePush) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *StopNoticePush) GetIntervalTime() uint32 {
	if m != nil {
		return m.IntervalTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BcastworldResp)(nil), "suoha.BcastworldResp")
	proto.RegisterType((*BcastMsgResp)(nil), "suoha.BcastMsgResp")
	proto.RegisterType((*StopNoticePush)(nil), "suoha.StopNoticePush")
}
func (m *BcastworldResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BcastworldResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(len(m.Content)))
	i += copy(dAtA[i:], m.Content)
	return i, nil
}

func (m *BcastMsgResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BcastMsgResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Msg == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("msg")
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.Msg.Size()))
		n1, err := m.Msg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *StopNoticePush) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopNoticePush) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.Id))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.Type))
	dAtA[i] = 0x18
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.Executed))
	dAtA[i] = 0x22
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(len(m.Content)))
	i += copy(dAtA[i:], m.Content)
	dAtA[i] = 0x28
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.StartTime))
	dAtA[i] = 0x30
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.EndTime))
	dAtA[i] = 0x38
	i++
	i = encodeVarintMsgBroadcast(dAtA, i, uint64(m.IntervalTime))
	return i, nil
}

func encodeVarintMsgBroadcast(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *BcastworldResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Content)
	n += 1 + l + sovMsgBroadcast(uint64(l))
	return n
}

func (m *BcastMsgResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovMsgBroadcast(uint64(l))
	}
	return n
}

func (m *StopNoticePush) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovMsgBroadcast(uint64(m.Id))
	n += 1 + sovMsgBroadcast(uint64(m.Type))
	n += 1 + sovMsgBroadcast(uint64(m.Executed))
	l = len(m.Content)
	n += 1 + l + sovMsgBroadcast(uint64(l))
	n += 1 + sovMsgBroadcast(uint64(m.StartTime))
	n += 1 + sovMsgBroadcast(uint64(m.EndTime))
	n += 1 + sovMsgBroadcast(uint64(m.IntervalTime))
	return n
}

func sovMsgBroadcast(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMsgBroadcast(x uint64) (n int) {
	return sovMsgBroadcast(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BcastworldResp) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgBroadcast
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BcastworldResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BcastworldResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMsgBroadcast(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("content")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BcastMsgResp) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgBroadcast
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BcastMsgResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BcastMsgResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &Dmsg{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMsgBroadcast(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("msg")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StopNoticePush) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgBroadcast
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopNoticePush: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopNoticePush: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			m.Executed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Executed |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntervalTime", wireType)
			}
			m.IntervalTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IntervalTime |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgBroadcast(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgBroadcast
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("id")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("type")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("executed")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("content")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgBroadcast(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgBroadcast
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgBroadcast
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMsgBroadcast
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsgBroadcast
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsgBroadcast(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsgBroadcast = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgBroadcast   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("msg_broadcast.proto", fileDescriptor_msg_broadcast_f26ad4061139d112) }

var fileDescriptor_msg_broadcast_f26ad4061139d112 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xcb, 0x4e, 0x32, 0x31,
	0x14, 0x80, 0xa7, 0x03, 0xfc, 0xc0, 0xe1, 0x92, 0x3f, 0xd5, 0x45, 0x63, 0x62, 0x21, 0xb8, 0xd1,
	0x85, 0xc4, 0xf8, 0x08, 0xc4, 0xad, 0xc6, 0xa0, 0x7b, 0x32, 0x4e, 0x4f, 0x86, 0x26, 0xb4, 0x9d,
	0x4c, 0x0f, 0x5e, 0xde, 0xc2, 0xc7, 0x62, 0xc9, 0xd2, 0x95, 0x31, 0xf0, 0x08, 0xbe, 0x80, 0x99,
	0x22, 0x64, 0x16, 0x6e, 0xbf, 0xef, 0x3b, 0x17, 0x38, 0x32, 0x3e, 0x9b, 0x3d, 0x15, 0x2e, 0x51,
	0x69, 0xe2, 0x69, 0x9c, 0x17, 0x8e, 0x1c, 0x6f, 0xf8, 0xa5, 0x9b, 0x27, 0x27, 0xff, 0x4b, 0x97,
	0x3a, 0x63, 0x9c, 0xdd, 0x89, 0xd1, 0x15, 0xf4, 0x27, 0x65, 0xf7, 0xe2, 0x8a, 0x85, 0x9a, 0xa2,
	0xcf, 0xb9, 0x84, 0x66, 0xea, 0x2c, 0xa1, 0x25, 0xc1, 0x86, 0xf1, 0x79, 0x7b, 0x52, 0x5f, 0x7d,
	0x0e, 0xa2, 0xe9, 0x1e, 0x8e, 0x2e, 0xa1, 0x1b, 0x26, 0x6e, 0x7d, 0x16, 0xfa, 0x53, 0xa8, 0x19,
	0x9f, 0x85, 0xb6, 0x73, 0xdd, 0x19, 0x87, 0x43, 0xe3, 0x1b, 0xe3, 0xb3, 0x69, 0xc9, 0x47, 0xdf,
	0x0c, 0xfa, 0x0f, 0xe4, 0xf2, 0x3b, 0x47, 0x3a, 0xc5, 0xfb, 0xa5, 0x9f, 0xf3, 0x63, 0x88, 0xb5,
	0x0a, 0x03, 0xbd, 0xdf, 0xe5, 0xb1, 0x56, 0x5c, 0x40, 0x9d, 0xde, 0x72, 0x14, 0x71, 0x85, 0x07,
	0xc2, 0x87, 0xd0, 0xc2, 0x57, 0x4c, 0x97, 0x84, 0x4a, 0xd4, 0x2a, 0xf6, 0x40, 0xab, 0x3f, 0xd7,
	0xff, 0xf8, 0x99, 0x9f, 0x01, 0x78, 0x4a, 0x0a, 0x9a, 0x91, 0x36, 0x28, 0x1a, 0x43, 0x76, 0xd8,
	0xd1, 0x0e, 0xfc, 0x51, 0x1b, 0xe4, 0x03, 0x68, 0xa1, 0x55, 0xbb, 0xe4, 0x5f, 0x25, 0x69, 0xa2,
	0x55, 0x21, 0xb8, 0x80, 0x9e, 0xb6, 0x84, 0xc5, 0x73, 0xb2, 0xd8, 0x55, 0xcd, 0x4a, 0xd5, 0xdd,
	0xab, 0x32, 0x9d, 0x88, 0xd5, 0x46, 0xb2, 0xf5, 0x46, 0xb2, 0xaf, 0x8d, 0x64, 0xef, 0x5b, 0x19,
	0xad, 0xb7, 0x32, 0xfa, 0xd8, 0xca, 0xe8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x98, 0x2d, 0xa5, 0x0e,
	0x9f, 0x01, 0x00, 0x00,
}
