// Generated by trunk/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: msg.proto
// Source: msg_base.proto
// Source: msg_common.proto
// Source: msg_broadcast.proto
// Source: msg_gm.proto
// Source: msg_lobby.proto
// Source: msg_role_common.proto
// Source: msg_login.proto
// Source: msg_role.proto
// Source: msg_room_6504.proto

package tbnn

import (
	"trunk/cellnet"
	"reflect"
	_ "trunk/cellnet/codec/gogopb"
	"trunk/cellnet/codec"
)

func NotWriteInit() {

	// msg.proto
	// msg_base.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*HeartbeatReq)(nil)).Elem(),
		ID:    51768,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*HeartbeatResp)(nil)).Elem(),
		ID:    27370,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*TimeReq)(nil)).Elem(),
		ID:    3639,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*TimeResp)(nil)).Elem(),
		ID:    11977,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PopupMsgResp)(nil)).Elem(),
		ID:    42613,
	})
	// msg_common.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*Undefined)(nil)).Elem(),
		ID:    30802,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*DmsgContent)(nil)).Elem(),
		ID:    40742,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*Dmsg)(nil)).Elem(),
		ID:    6155,
	})
	// msg_broadcast.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BcastWorldResp)(nil)).Elem(),
		ID:    61391,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BcastMsgResp)(nil)).Elem(),
		ID:    6446,
	})
	// msg_gm.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmCardInfo)(nil)).Elem(),
		ID:    39866,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmCardReq)(nil)).Elem(),
		ID:    20758,
	})
	// msg_lobby.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoomInfo)(nil)).Elem(),
		ID:    56329,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoomInfoPush)(nil)).Elem(),
		ID:    14281,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*StartMatchReq)(nil)).Elem(),
		ID:    28739,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*StartMatchResp)(nil)).Elem(),
		ID:    53845,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*CancelMatchReq)(nil)).Elem(),
		ID:    62971,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*CancelMatchResp)(nil)).Elem(),
		ID:    3853,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LeaveRoomReq)(nil)).Elem(),
		ID:    21042,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LeaveRoomResp)(nil)).Elem(),
		ID:    61988,
	})
	// msg_role_common.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoleInfo)(nil)).Elem(),
		ID:    43166,
	})
	// msg_login.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginReq)(nil)).Elem(),
		ID:    18049,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginResp)(nil)).Elem(),
		ID:    28755,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginAccountReq)(nil)).Elem(),
		ID:    53070,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*KickResp)(nil)).Elem(),
		ID:    6428,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UpdateTokenResp)(nil)).Elem(),
		ID:    10622,
	})
	// msg_role.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*ChipsPush)(nil)).Elem(),
		ID:    8919,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetAvatarReq)(nil)).Elem(),
		ID:    13523,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetAvatarResp)(nil)).Elem(),
		ID:    10469,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetChipsReq)(nil)).Elem(),
		ID:    19071,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UpdateGetReq)(nil)).Elem(),
		ID:    37675,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetWalletReq)(nil)).Elem(),
		ID:    29937,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetWalletResp)(nil)).Elem(),
		ID:    27843,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetWalletReq)(nil)).Elem(),
		ID:    7037,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetWalletResp)(nil)).Elem(),
		ID:    58575,
	})
	// msg_room_6504.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PokerInfo)(nil)).Elem(),
		ID:    63757,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*EnterRoomPush)(nil)).Elem(),
		ID:    7291,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SyncRoomStagePush)(nil)).Elem(),
		ID:    6318,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*MultiListPush)(nil)).Elem(),
		ID:    40519,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BetMultiReq)(nil)).Elem(),
		ID:    48750,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BetMultiPush)(nil)).Elem(),
		ID:    46118,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*DealCardResp)(nil)).Elem(),
		ID:    49994,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SpreadCardReq)(nil)).Elem(),
		ID:    23809,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SpreadCardPush)(nil)).Elem(),
		ID:    9497,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SpreadInfo)(nil)).Elem(),
		ID:    10859,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SettleChipPush)(nil)).Elem(),
		ID:    13109,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SettleInfo)(nil)).Elem(),
		ID:    6365,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*CodeInfoResp)(nil)).Elem(),
		ID:    39777,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*ReloginInfoResp)(nil)).Elem(),
		ID:    61942,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoomRoleInfo)(nil)).Elem(),
		ID:    41499,
	})
}
