// Generated by trunk/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: msg_base.proto
// Source: msg_common.proto
// Source: msg_broadcast.proto
// Source: msg_gm.proto
// Source: msg_lobby.proto
// Source: msg_role_common.proto
// Source: msg_login.proto
// Source: msg_role.proto
// Source: msg_room_zjh.proto

package jdzjh

import (
	"trunk/cellnet"
	"reflect"
	_ "trunk/cellnet/codec/gogopb"
	"trunk/cellnet/codec"
)

func NotWriteInit() {

	// msg_base.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*HeartbeatReq)(nil)).Elem(),
		ID:    15392,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*HeartbeatResp)(nil)).Elem(),
		ID:    6610,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*TimeReq)(nil)).Elem(),
		ID:    44831,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*TimeResp)(nil)).Elem(),
		ID:    60593,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PopupMsgResp)(nil)).Elem(),
		ID:    6237,
	})
	// msg_common.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*Undefined)(nil)).Elem(),
		ID:    62266,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*DmsgContent)(nil)).Elem(),
		ID:    29710,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*Dmsg)(nil)).Elem(),
		ID:    8691,
	})
	// msg_broadcast.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BcastworldResp)(nil)).Elem(),
		ID:    43991,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*BcastMsgResp)(nil)).Elem(),
		ID:    35606,
	})
	// msg_gm.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmCardInfo)(nil)).Elem(),
		ID:    29602,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmCardReq)(nil)).Elem(),
		ID:    52222,
	})
	// msg_lobby.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoomInfo)(nil)).Elem(),
		ID:    39409,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoomInfoPush)(nil)).Elem(),
		ID:    43441,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*StartMatchReq)(nil)).Elem(),
		ID:    7979,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*StartMatchResp)(nil)).Elem(),
		ID:    24125,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*CancelMatchReq)(nil)).Elem(),
		ID:    33251,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*CancelMatchResp)(nil)).Elem(),
		ID:    6133,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LeaveRoomReq)(nil)).Elem(),
		ID:    50202,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LeaveRoomResp)(nil)).Elem(),
		ID:    41228,
	})
	// msg_role_common.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*RoleInfo)(nil)).Elem(),
		ID:    26246,
	})
	// msg_login.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginReq)(nil)).Elem(),
		ID:    1129,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginResp)(nil)).Elem(),
		ID:    60219,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LoginAccountReq)(nil)).Elem(),
		ID:    55350,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*KickResp)(nil)).Elem(),
		ID:    55044,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UpdateTokenResp)(nil)).Elem(),
		ID:    12902,
	})
	// msg_role.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*ChipsPush)(nil)).Elem(),
		ID:    40383,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetAvatarReq)(nil)).Elem(),
		ID:    42683,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetAvatarResp)(nil)).Elem(),
		ID:    55245,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetChipsReq)(nil)).Elem(),
		ID:    8039,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UpdateGtReq)(nil)).Elem(),
		ID:    16750,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetWalletReq)(nil)).Elem(),
		ID:    59097,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GetWalletResp)(nil)).Elem(),
		ID:    7083,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetWalletReq)(nil)).Elem(),
		ID:    36197,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*SetWalletResp)(nil)).Elem(),
		ID:    37815,
	})
	// msg_room_zjh.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GamePlayerInfoPush)(nil)).Elem(),
		ID:    38875,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PlayerInfo)(nil)).Elem(),
		ID:    18337,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GamePush)(nil)).Elem(),
		ID:    19202,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UserOperationReq)(nil)).Elem(),
		ID:    15776,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*UserOperationResp)(nil)).Elem(),
		ID:    19282,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GameSettlementPush)(nil)).Elem(),
		ID:    62311,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GameResult)(nil)).Elem(),
		ID:    37345,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmReq)(nil)).Elem(),
		ID:    50724,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PlayerCards)(nil)).Elem(),
		ID:    51810,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*GmResp)(nil)).Elem(),
		ID:    58454,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PlayerReconnect)(nil)).Elem(),
		ID:    63894,
	})
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*PlayerMsg)(nil)).Elem(),
		ID:    51228,
	})
}
